#version: '2.4'

# environmental variables *for Docker Compose* will be loaded from a `.env` file
# in the same directory as this file

# mods are shared on the network using Samba (on the host)

# Starbound
services:
  vanilla:
    build: ../../build/starbound
    # container_name: starbound
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_USERDIR}/volumes/starbound-app:/app
      - ${DOCKER_USERDIR}/volumes/starbound-config:/config
    ports:
      - 21025:21025
    labels:
      - traefik.enable=false

  frackin-universe:
    build: ../../build/starbound
    # container_name: starbound_fu
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_USERDIR}/volumes/starbound-app:/app:ro
      - ${DOCKER_USERDIR}/volumes/starbound-fu-config:/config
    ports:
      - 21030:21025
    labels:
      - traefik.enable=false

networks:
  default:
    external: true
    name: meta_external
