version: '3.7'
services:
  app:
    image: eugenci/papermerge:latest
    # container_name: papermerge_service
    command: python3 /opt/papermerge/manage.py runserver 0.0.0.0:8000
    ports:
      - 9952:8000
    depends_on:
      - db
    volumes:
      - ${DOCKER_USERDIR}/volumes/papermerge/media:/opt/media
      - ${DOCKER_USERDIR}/volumes/papermerge/broker_queue:/opt/broker/queue
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.stage

  db:
    image: postgres:11.7
    # container_name: postgres_db
    volumes:
      - ${DOCKER_USERDIR}/volumes/papermerge/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname

  worker:
    image: eugenci/papermerge-worker:latest
    # container_name: papermerge_worker
    command: bash -c "cd /opt/papermerge-worker && celery worker -A pmworker.celery -Q papermerge -l info"
    volumes:
      - ${DOCKER_USERDIR}/volumes/papermerge/media:/opt/media
      - ${DOCKER_USERDIR}/volumes/papermerge/broker_queue:/opt/broker/queue
    environment:
      - CELERY_CONFIG_MODULE=config
      - C_FORCE_ROOT=True

# volumes:
#   postgres_data:
#   broker_queue:
#   media_root:
