# version: '2.4'

# environmental variables *for Docker Compose* will be loaded from a `.env` file
# in the same directory as this file

services:
  ngircd:
    image: lscr.io/linuxserver/ngircd
    container_name: ngircd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_USERDIR}/volumes/ngircd:/config
    ports:
      - 6667:6667
    restart: unless-stopped

  quassel-core:
    image: lscr.io/linuxserver/quassel-core
    container_name: quassel-core
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - RUN_OPTS=--config-from-environment  # run the first time without...
      - DB_BACKEND=SQLite
      - AUTH_AUTHENTICATOR=Database
    volumes:
      - ${DOCKER_USERDIR}/volumes/quassel-core:/config
    ports:
      - 9958:4242
      - 113:10113  # optional, ident server
    restart: unless-stopped
    # can use a PostreSQL database...

  thelounge:
    image: lscr.io/linuxserver/thelounge
    container_name: thelounge
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_USERDIR}/volumes/thelounge:/config
    ports:
      - 9960:9000
    restart: unless-stopped

networks:
  default:
    name: meta_external
    external: true
