#version: '2.4'

# environmental variables *for Docker Compose* will be loaded from a `.env` file
# in the same directory as this file

services:

  bedrock_peaceful:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft_bedrock_peaceful
    restart: unless-stopped
    environment:
      - EULA=TRUE
      # - VERSION=${MINECRAFT_VERSION}
      - UID=${PUID}
      - GID=${PGID}
      - GAMEMODE=survival
      - DIFFICULTY=peaceful
      - SERVER_NAME=Normandie
      - VIEW_DISTANCE=72
      - MAX_THREADS=8
      - LEVEL_NAME=Minchin Family
    volumes:
      - ${DOCKER_USERDIR}/volumes/minecraft:/data
    ports:
      - 19132:19132/udp
    stdin_open: true
    tty: true
    # labels:
    #   # better to just enable port forwarding
    #   - traefik.enable=true
    #   - traefik.http.routers.minecraft-local.rule=Host("minecraft.${LOCAL_DOMAIN_NAME}")
    #   - traefik.http.routers.minecraft-local.entrypoint=minecraft

    #   - traefik.http.routers.minecraft.rule=Host("${PUBLIC_DOMAIN_NAME}")
    #   - traefik.http.routers.minecraft.entrypoint=minecraft

   # bedrock_survival:
   # image: itzg/minecraft-bedrock-server
   # restart: unless-stopped
   # environment:
   #   - EULA=TRUE
   #   # - VERSION=${MINECRAFT_VERSION}
   #   - UID=${PUID}
   #   - GID=${PGID}
   #   - GAMEMODE=survival
   #   - DIFFICULTY=normal
   #   - SERVER_NAME=Normandie Survival
   #   - SERVER_PORT=19134
   #   - VIEW_DISTANCE=72
   #   - MAX_THREADS=8
   #   - LEVEL_NAME=Minchin Family Survival
   # volumes:
   #   - ${DOCKER_USERDIR}/volumes/minecraft-survival:/data
   # ports:
   #   - 19134:19134/udp
   # labels:
   #   - traefik.enable=true
   #   - traefik.http.routers.minecraft-survival.rule=Host("minecraft-survival.${LOCAL_DOMAIN_NAME}")

  backup:
    image: kaiede/minecraft-bedrock-backup
    # name: bedrock_backup
    restart: unless-stopped
    depends_on:
      - bedrock_peaceful
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - TZ=${TZ}
      - BACKUP_INTERVAL=3h
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_USERDIR}/volumes/minecraft:/server
      - ${NAS_DIR}/home/trocadero/minecraft:/backups
    stdin_open: true
    tty: true

networks:
  default:
    external: true
    name: meta_external
