version: '2.4'

# environmental variables *for Docker Compose* will be loaded from a `.env` file
# in the same directory as this file

services:
  ddns-base:
    build: ../../build/ddns  # also at minchinweb/ddns:latest
    container_name: ddns_${PUBLIC_DOMAIN_NAME}
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DDNS_DOMAIN_NAME=${PUBLIC_DOMAIN_NAME}
      - DDNS_UPDATE_URL=${DDNS_UPDATE_URL}
      - DDNS_KEY=${DDNS_KEY_NORMANDIE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=false

  ddns-audioserve:
    # for audioserve
    build: ../../build/ddns
    container_name: ddns_ab.${PUBLIC_DOMAIN_NAME}
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DDNS_DOMAIN_NAME=ab.${PUBLIC_DOMAIN_NAME}
      - DDNS_UPDATE_URL=${DDNS_UPDATE_URL}
      - DDNS_KEY=${DDNS_KEY_AB}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=false

  ddns-bitwarden:
    # for Bitwarden_RS
    build: ../../build/ddns
    container_name: ddns_vault.${PUBLIC_DOMAIN_NAME}
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DDNS_DOMAIN_NAME=vault.${PUBLIC_DOMAIN_NAME}
      - DDNS_UPDATE_URL=${DDNS_UPDATE_URL}
      - DDNS_KEY=${DDNS_KEY_VAULT}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=false

networks:
  default:
    external:
      name: frontend_external
