version: '2.4'

# environmental variables *for Docker Compose* will be loaded from a `.env` file
# in the same directory as this file

services:
  ddns-base:
    # build: ../../build/ddns  # also at minchinweb/ddns:latest
    image: minchinweb/ddns
    container_name: ddns_${PUBLIC_DOMAIN_NAME}
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DDNS_DOMAIN_NAME=${PUBLIC_DOMAIN_NAME}
      - DDNS_UPDATE_URL=${DDNS_UPDATE_URL}
      - DDNS_KEY=${DDNS_KEY_NORMANDIE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=false

  ddns-audioserve:
    # for audioserve
    # build: ../../build/ddns
    image: minchinweb/ddns
    container_name: ddns_ab.${PUBLIC_DOMAIN_NAME}
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DDNS_DOMAIN_NAME=ab.${PUBLIC_DOMAIN_NAME}
      - DDNS_UPDATE_URL=${DDNS_UPDATE_URL}
      - DDNS_KEY=${DDNS_KEY_AB}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=false


  ddns-bitwarden:
    # build: ../../build/ddns
    image: minchinweb/ddns
    container_name: ddns_vault.${PUBLIC_DOMAIN_NAME}
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DDNS_DOMAIN_NAME=vault.${PUBLIC_DOMAIN_NAME}
      - DDNS_UPDATE_URL=${DDNS_UPDATE_URL}
      - DDNS_KEY=${DDNS_KEY_VAULT}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=false


  ddns-booksonic:
    # for booksonic-air
    # build: ../../build/ddns
    image: minchinweb/ddns
    container_name: ddns_booksonic.${PUBLIC_DOMAIN_NAME}
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DDNS_DOMAIN_NAME=booksonic.${PUBLIC_DOMAIN_NAME}
      - DDNS_UPDATE_URL=${DDNS_UPDATE_URL}
      - DDNS_KEY=${DDNS_KEY_BOOKSONIC}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=false

  # ddns-minecraft:
  #   # for Minecraft (Peaceful)
  #   # build: ../../build/ddns
  #   image: minchinweb/ddns
  #   container_name: ddns_minecraft.${PUBLIC_DOMAIN_NAME}
  #   restart: unless-stopped
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - DDNS_DOMAIN_NAME=mc.${PUBLIC_DOMAIN_NAME}
  #     - DDNS_UPDATE_URL=${DDNS_UPDATE_URL}
  #     - DDNS_KEY=${DDNS_KEY_MINECRAFT}
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #   labels:
  #     - traefik.enable=false

  ddns-navidrome:
    # for Navidrome
    # build: ../../build/ddns
    image: minchinweb/ddns
    container_name: ddns_music.${PUBLIC_DOMAIN_NAME}
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - DDNS_DOMAIN_NAME=music.${PUBLIC_DOMAIN_NAME}
      - DDNS_UPDATE_URL=${DDNS_UPDATE_URL}
      - DDNS_KEY=${DDNS_KEY_MUSIC}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=false
    


networks:
  default:
    external:
      name: meta_external
